# ARREGLOS Y CLASES

## MATRICES
Una matriz es un arreglo de $m$x$[texto del vínculo](https://)n$ elementos

\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix}

In [3]:
#Generar una lista
A= [[1,2,3],[4,5,6],[7,8,9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
#Vamos a generar otra lista
B=[[21,34,40], [71,17,77],[73,81,28]]
print(B)

[[21, 34, 40], [71, 17, 77], [73, 81, 28]]


In [6]:
A+B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]

In [7]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
A[0][0]
# A[0,0] NO se puede, debe escribirse como esta arriba [0](primer lista)[0]primer valor

1

##VECTORES Y LISTAS



In [17]:
L=A[0]
M=B[0]

[1, 2, 3, 21, 34, 40]

In [25]:
a=L[0]
b=M[0]
a+b

22

In [26]:
a==1

True

### SUMA DE VECTORES


In [27]:
len(L)

True

In [31]:
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma

[22, 36, 43]

In [35]:
suma=[L[i]+M[i] for i in range(3)]
suma

[22, 36, 43]

### CREACIÓN DE FUNCIONES GLOBALES
La función para crear funciones es `def` que se cierra con un debug (`print` o `return`)

In [38]:
def Hola():
  print("Hola, me llamo Marina")

In [39]:
Hola()

Hola, me llamo Marina


In [45]:
def saludar(s,n):
  print(f"Hola, me llamo {s} y tengo {n} años")

In [46]:
saludar("Marina", 18)

Hola, me llamo Marina y tengo 18 años


In [63]:
def par(x):
  for x in range(10):
    if x%2==0:
      print(f"{x} es par")
    else:
      print(f"{x} es impar")

In [64]:
par(10)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [65]:
def sumavectorial(L,M):
  x = [L[i]+M[i] for i in range(len(L))]
  return x

In [66]:
L = [1, 2, 3]
M = [21, 34, 40]

sumavectorial(L,M)

[22, 36, 43]

## MÓDULOS O LIBRERÍA
Una librería en POO es un conjunto de clases y métodos que te ayudan a construir programas de manera más rápida, fácil y eficiente. Es como tener un kit de herramientas lleno de funcionalidades listas para usar.

In [68]:
import math
from math import sqrt, pi

In [70]:
pi

3.141592653589793

#EL MÓDULO NumPy

La función `array`

In [71]:
#array convierte listas en un vector
import numpy as np
L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [73]:
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [74]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])